In [2]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [29]:
df = pd.read_csv("dataset/dataset_yanti.csv")

In [30]:
df

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,...,P12,P13,P14,P15,P16,P17,P18,P19,P20,Major
0,4,5,4,5,5,4,3,3,4,5,...,4,5,4,2,4,5,3,4,2,ComputerScience
1,4,3,3,3,4,3,2,2,3,4,...,3,4,3,1,3,4,2,3,1,ComputerScience
2,5,5,5,5,4,5,4,3,5,5,...,5,5,4,2,5,5,4,5,2,ComputerScience
3,3,4,3,4,3,4,2,2,3,4,...,3,4,3,1,3,4,2,3,1,ComputerScience
4,4,5,4,5,5,4,3,3,4,5,...,4,5,4,2,4,5,3,4,2,ComputerScience
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,3,5,4,2,3,4,3,2,4,1,...,2,3,1,4,3,5,2,4,1,NaN
246,5,4,3,2,4,5,3,2,4,1,...,2,3,1,4,3,5,2,4,1,NaN
247,4,3,5,2,4,5,3,2,4,1,...,2,3,1,4,3,5,2,4,1,NaN
248,5,4,3,2,5,4,3,2,4,1,...,2,3,1,4,3,5,2,4,1,NaN
249,4,2,5,3,4,3,3,2,4,1,...,2,3,1,4,3,5,2,4,1,NaN

In [31]:
df = df.fillna('ComputerScience')

In [32]:
df

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,...,P12,P13,P14,P15,P16,P17,P18,P19,P20,Major
0,4,5,4,5,5,4,3,3,4,5,...,4,5,4,2,4,5,3,4,2,ComputerScience
1,4,3,3,3,4,3,2,2,3,4,...,3,4,3,1,3,4,2,3,1,ComputerScience
2,5,5,5,5,4,5,4,3,5,5,...,5,5,4,2,5,5,4,5,2,ComputerScience
3,3,4,3,4,3,4,2,2,3,4,...,3,4,3,1,3,4,2,3,1,ComputerScience
4,4,5,4,5,5,4,3,3,4,5,...,4,5,4,2,4,5,3,4,2,ComputerScience
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,3,5,4,2,3,4,3,2,4,1,...,2,3,1,4,3,5,2,4,1,ComputerScience
246,5,4,3,2,4,5,3,2,4,1,...,2,3,1,4,3,5,2,4,1,ComputerScience
247,4,3,5,2,4,5,3,2,4,1,...,2,3,1,4,3,5,2,4,1,ComputerScience
248,5,4,3,2,5,4,3,2,4,1,...,2,3,1,4,3,5,2,4,1,ComputerScience
249,4,2,5,3,4,3,3,2,4,1,...,2,3,1,4,3,5,2,4,1,ComputerScience

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   P1      250 non-null    int64
 1   P2      250 non-null    int64
 2   P3      250 non-null    int64
 3   P4      250 non-null    int64
 4   P5      250 non-null    int64
 5   P6      250 non-null    int64
 6   P7      250 non-null    int64
 7   P8      250 non-null    int64
 8   P9      250 non-null    int64
 9   P10     250 non-null    int64
 10  P11     250 non-null    int64
 11  P12     250 non-null    int64
 12  P13     250 non-null    int64
 13  P14     250 non-null    int64
 14  P15     250 non-null    int64
 15  P16     250 non-null    int64
 16  P17     250 non-null    int64
 17  P18     250 non-null    int64
 18  P19     250 non-null    int64
 19  P20     250 non-null    int64
 20  Major   250 non-null    object
dtypes: int64(20), object(1)
memory usage: 41.1+ KB

In [34]:
df['Major'].value_counts()

Major
ComputerScience    250
Name: count, dtype: int64

In [7]:
X = df.iloc[:,0:27]
y = df['Jurusan']

In [8]:
X

,kegiatan kreatif dan seni,pemecahan masalah matematika dan logika,bekerja dengan angka dan statistik,menikmati membaca dan menulis,data dan angka,senang bermain musik atau menyanyi,memiliki keterampilan komputer yang baik,menikmati berbicara di depan umum,Menggunakan penalaran dalam selesaikan masalah,Peka dengan perasaan orang lain,...,Rasa ingin tahu tinggi,Membantu orang lain,Pelayanan Masyarakat,Traveling,mudah menghafal teori,penasaran dengan IPA,menyukai bertanya dan berpendapat,Memperhatikan Estetika,Komunikasi visual,mudah menjelaskan sesuatu
0,tidak menyukai,sangat menyukai,menyukai,tidak terlalu menyukai,menyukai,tidak menyukai,iya,tidak menyukai,iya,tidak,...,iya,menyukai,tidak menyukai,tidak menyukai,tidak,iya,tidak menyukai,tidak menyukai,tidak menyukai,terkadang
1,tidak menyukai,menyukai,sangat menyukai,tidak terlalu menyukai,sangat menyukai,tidak menyukai,tidak,sangat menyukai,terkadang,terkadang,...,iya,sangat menyukai,sangat menyukai,menyukai,tidak,iya,menyukai,menyukai,tidak menyukai,terkadang
2,tidak terlalu menyukai,tidak terlalu menyukai,tidak menyukai,menyukai,tidak menyukai,tidak menyukai,tidak,menyukai,terkadang,iya,...,iya,sangat menyukai,sangat menyukai,tidak menyukai,iya,iya,tidak menyukai,menyukai,tidak menyukai,iya
3,tidak menyukai,menyukai,sangat menyukai,tidak terlalu menyukai,sangat menyukai,tidak menyukai,terkadang,tidak menyukai,iya,tidak,...,terkadang,tidak menyukai,tidak menyukai,tidak menyukai,terkadang,iya,tidak menyukai,tidak menyukai,tidak menyukai,terkadang
4,sangat menyukai,tidak menyukai,tidak menyukai,sangat menyukai,tidak menyukai,sangat menyukai,tidak,sangat menyukai,tidak,tidak,...,terkadang,tidak menyukai,tidak menyukai,sangat menyukai,iya,tidak,menyukai,sangat menyukai,sangat menyukai,iya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,menyukai,menyukai,sangat menyukai,tidak terlalu menyukai,sangat menyukai,tidak menyukai,tidak,sangat menyukai,terkadang,terkadang,...,iya,sangat menyukai,menyukai,menyukai,tidak,iya,menyukai,menyukai,tidak menyukai,terkadang
136,menyukai,tidak terlalu menyukai,tidak menyukai,menyukai,tidak menyukai,tidak menyukai,tidak,menyukai,terkadang,iya,...,iya,sangat menyukai,sangat menyukai,tidak menyukai,iya,iya,tidak menyukai,menyukai,tidak menyukai,iya
137,tidak menyukai,menyukai,sangat menyukai,tidak terlalu menyukai,sangat menyukai,tidak menyukai,tidak,sangat menyukai,terkadang,terkadang,...,iya,sangat menyukai,menyukai,menyukai,tidak,iya,menyukai,tidak menyukai,tidak menyukai,terkadang
138,sangat menyukai,tidak terlalu menyukai,tidak menyukai,menyukai,tidak menyukai,tidak menyukai,tidak,menyukai,terkadang,iya,...,iya,sangat menyukai,sangat menyukai,tidak menyukai,iya,iya,tidak menyukai,sangat menyukai,sangat menyukai,iya
139,tidak menyukai,menyukai,sangat menyukai,tidak terlalu menyukai,sangat menyukai,tidak menyukai,tidak,sangat menyukai,terkadang,terkadang,...,iya,sangat menyukai,menyukai,menyukai,tidak,iya,menyukai,tidak menyukai,tidak menyukai,terkadang

In [9]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

for column in df.columns:
    if df[column].dtype == 'object' :
        df[column + '_encoded'] = label_encoder.fit_transform(df[column])

print(df)

    kegiatan kreatif dan seni pemecahan masalah matematika dan logika
0              tidak menyukai                          sangat menyukai  \
1              tidak menyukai                                 menyukai
2      tidak terlalu menyukai                   tidak terlalu menyukai
3              tidak menyukai                                 menyukai
4             sangat menyukai                           tidak menyukai
..                        ...                                      ...
135                  menyukai                                 menyukai
136                  menyukai                   tidak terlalu menyukai
137            tidak menyukai                                 menyukai
138           sangat menyukai                   tidak terlalu menyukai
139            tidak menyukai                                 menyukai

    bekerja dengan angka dan statistik menikmati membaca dan menulis
0                             menyukai        tidak terlalu menyukai  \
1                      sangat menyukai        tidak terlalu menyukai
2                       tidak menyukai                      menyukai
3                      sangat menyukai        tidak terlalu menyukai
4                       tidak menyukai               sangat menyukai
..                                 ...                           ...
135                    sangat menyukai        tidak terlalu menyukai
136                     tidak menyukai                      menyukai
137                    sangat menyukai        tidak terlalu menyukai
138                     tidak menyukai                      menyukai
139                    sangat menyukai        tidak terlalu menyukai

      data dan angka senang bermain musik atau menyanyi
0           menyukai                     tidak menyukai  \
1    sangat menyukai                     tidak menyukai
2     tidak menyukai                     tidak menyukai
3    sangat menyukai                     tidak menyukai
4     tidak menyukai                    sangat menyukai
..               ...                                ...
135  sangat menyukai                     tidak menyukai
136   tidak menyukai                     tidak menyukai
137  sangat menyukai                     tidak menyukai
138   tidak menyukai                     tidak menyukai
139  sangat menyukai                     tidak menyukai

    memiliki keterampilan komputer yang baik
0                                        iya  \
1                                      tidak
2                                      tidak
3                                  terkadang
4                                      tidak
..                                       ...
135                                    tidak
136                                    tidak
137                                    tidak
138                                    tidak
139                                    tidak

    menikmati berbicara di depan umum
0                      tidak menyukai  \
1                     sangat menyukai
2                            menyukai
3                      tidak menyukai
4                     sangat menyukai
..                                ...
135                   sangat menyukai
136                          menyukai
137                   sangat menyukai
138                          menyukai
139                   sangat menyukai

    Menggunakan penalaran dalam selesaikan masalah
0                                              iya  \
1                                        terkadang
2                                        terkadang
3                                              iya
4                                            tidak
..                                             ...
135                                      terkadang
136                                      terkadang
137                                      terkadang
138                                      terkadang
139                                      terkadang

    Peka dengan perasaan orang lain  ... Membantu orang lain_encoded
0                             tidak  ...                           0  \
1                         terkadang  ...                           1
2                               iya  ...                           1
3                             tidak  ...                           2
4                             tidak  ...                           2
..                              ...  ...                         ...
135                       terkadang  ...                           1
136                             iya  ...                           1
137                       terkadang  ...                           1
138                             iya  ...                           1
139                       terkadang  ...                           1

    Pelayanan Masyarakat_encoded Traveling_encoded
0                              2                 3  \
1                              1                 0
2                              1                 3
3                              2                 3
4                              2                 1
..                           ...               ...
135                            0                 0
136                            1                 3
137                            0                 0
138                            1                 3
139                            0                 0

    mudah menghafal teori_encoded penasaran dengan IPA_encoded
0                               2                            0  \
1                               2                            0
2                               0                            0
3                               1                            0
4                               0                            2
..                            ...                          ...
135                             2                            0
136                             0                            0
137                             2                            0
138                             0                            0
139                             2                            0

    menyukai bertanya dan berpendapat_encoded Memperhatikan Estetika_encoded
0                                           2                              2  \
1                                           0                              0
2                                           2                              0
3                                           2                              2
4                                           0                              1
..                                        ...                            ...
135                                         0                              0
136                                         2                              0
137                                         0                              2
138                                         2                              1
139                                         0                              2

    Komunikasi visual_encoded mudah menjelaskan sesuatu_encoded
0                           2                                 1  \
1                           2                                 1
2                           2                                 0
3                           2                                 1
4                           1                                 0
..                        ...                               ...
135                         2                                 1
136                         2                                 0
137                         2                                 1
138                         1                                 0
139                         2                                 1

    Jurusan_encoded
0                 2
1                 1
2                 7
3                14
4                18
..              ...
135              21
136               6
137               4
138              27
139              19

[140 rows x 56 columns]

In [10]:
df = df.iloc[:,27:-1]

In [11]:
df.head()

,Jurusan,kegiatan kreatif dan seni_encoded,pemecahan masalah matematika dan logika _encoded,bekerja dengan angka dan statistik_encoded,menikmati membaca dan menulis_encoded,data dan angka_encoded,senang bermain musik atau menyanyi_encoded,memiliki keterampilan komputer yang baik_encoded,menikmati berbicara di depan umum_encoded,Menggunakan penalaran dalam selesaikan masalah_encoded,...,Rasa ingin tahu tinggi_encoded,Membantu orang lain_encoded,Pelayanan Masyarakat_encoded,Traveling_encoded,mudah menghafal teori_encoded,penasaran dengan IPA_encoded,menyukai bertanya dan berpendapat_encoded,Memperhatikan Estetika_encoded,Komunikasi visual_encoded,mudah menjelaskan sesuatu_encoded
0,Teknik Informatika,2,1,0,2,0,2,0,2,0,...,0,0,2,3,2,0,2,2,2,1
1,Statistika,2,0,1,2,1,2,2,1,1,...,0,1,1,0,2,0,0,0,2,1
2,farmasi,3,3,2,0,2,2,2,0,1,...,0,1,1,3,0,0,2,0,2,0
3,matematika,2,0,1,2,1,2,1,2,0,...,1,2,2,3,1,0,2,2,2,1
4,seni,1,2,2,1,2,0,2,1,2,...,1,2,2,1,0,2,0,1,1,0

In [12]:
X = df.iloc[:,1:28]
y = df['Jurusan']

In [13]:
X

,kegiatan kreatif dan seni_encoded,pemecahan masalah matematika dan logika _encoded,bekerja dengan angka dan statistik_encoded,menikmati membaca dan menulis_encoded,data dan angka_encoded,senang bermain musik atau menyanyi_encoded,memiliki keterampilan komputer yang baik_encoded,menikmati berbicara di depan umum_encoded,Menggunakan penalaran dalam selesaikan masalah_encoded,Peka dengan perasaan orang lain_encoded,...,Rasa ingin tahu tinggi_encoded,Membantu orang lain_encoded,Pelayanan Masyarakat_encoded,Traveling_encoded,mudah menghafal teori_encoded,penasaran dengan IPA_encoded,menyukai bertanya dan berpendapat_encoded,Memperhatikan Estetika_encoded,Komunikasi visual_encoded,mudah menjelaskan sesuatu_encoded
0,2,1,0,2,0,2,0,2,0,2,...,0,0,2,3,2,0,2,2,2,1
1,2,0,1,2,1,2,2,1,1,1,...,0,1,1,0,2,0,0,0,2,1
2,3,3,2,0,2,2,2,0,1,0,...,0,1,1,3,0,0,2,0,2,0
3,2,0,1,2,1,2,1,2,0,2,...,1,2,2,3,1,0,2,2,2,1
4,1,2,2,1,2,0,2,1,2,2,...,1,2,2,1,0,2,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,0,0,1,2,1,2,2,1,1,1,...,0,1,0,0,2,0,0,0,2,1
136,0,3,2,0,2,2,2,0,1,0,...,0,1,1,3,0,0,2,0,2,0
137,2,0,1,2,1,2,2,1,1,1,...,0,1,0,0,2,0,0,2,2,1
138,1,3,2,0,2,2,2,0,1,0,...,0,1,1,3,0,0,2,1,1,0
139,2,0,1,2,1,2,2,1,1,1,...,0,1,0,0,2,0,0,2,2,1

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [15]:
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [16]:
print("akurasi:" ,metrics.accuracy_score(y_test, y_pred))

akurasi: 0.09523809523809523

In [17]:
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [18]:
print("akurasi:" ,metrics.accuracy_score(y_test, y_pred))

akurasi: 0.11904761904761904

In [19]:
from sklearn.metrics import confusion_matrix
conf = confusion_matrix(y_test, y_pred)
print('confusion_matrix\n\n', conf)

confusion_matrix

 [[0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 2 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 2 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

In [6]:
import csv

# Specify the string you want to add
string_to_add = 'Sociology'

# Read the CSV file and store its contents
with open('dataset/sosiologi.csv', 'r') as file:
    reader = csv.reader(file)
    rows = list(reader)

# Modify each row by appending the string
for row in rows:
    row.append(string_to_add)

# Write the updated data back to the CSV file
with open('dataset/Sociology.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(rows)